[auth]
site_url = "https://mansour-cyber.github.io/healthy-life/"
additional_redirect_urls = ["https://mansour-cyber.github.io/healthy-life/"]

[auth.email]
enable_signup = true
enable_confirmations = true
double_confirm_changes = true

[auth.email.template.confirmation]
subject = "أكد بريدك في صحتي العائلية"
content_path = "./templates/confirmation.html"

[auth.email.template.invite]
subject = "دعوة عضوية في صحتي العائلية"
content_path = "./templates/invite.html"
